### ISSUE TITLE
vecnil has non-zero length

### ISSUE THREAD

**Issue by mpcsh** [david-christiansen/pie-hs#10]
I was trying out the faulty definition of `peas` in frame 7:5 of The Little Typer:
```scheme
(define peas
  (lambda (how-many-peas)
    (rec-Nat how-many-peas
      (the (Vec Atom 0) vecnil)
      (lambda (l-1 peas_l-1)
        (vec:: 'pea peas_l-1)))))
```
I loaded the file in the REPL with `:load` and was met with the following error:
```
chapter7.pie:12.9-12.30:
          (vec:: 'pea peas_l-1)))))
          ^-------------------^
vecnil has a non-zero length, but was used in a context where 0 length is expected.
```
It seems to me that either there's a bug in the inferrer causing a bad annotation to be given to `vecnil`, or there's a simple bug in the error message constructor.

For comparison, the Racket implementation gives this error:
```
vec:: requires that the length have add1 on top, not zero
```
Which is still a bit confusing to me, but is consistent.

**Comment by david-christiansen** [comment]
The bug is in the error message - thanks for reporting!

**Comment by david-christiansen** [comment]
Here's how the type checker is working: it starts with the target `how-many-peas` and cheks that it's a `Nat`. It then synthesizes the type `(Vec Atom zero)` for the base. It then checks that the step is a `(-> Nat (Vec Atom zero) (Vec Atom zero))`. Part of checking that step is ensuring that the body is a `(Vec Atom zero)`, but it finds a `vec::`, which requires that the length's value have `add1` at the top.

**Comment by david-christiansen** [comment]
Sinds bef697d, the message is:
```
Π> (claim peas (Pi ((how-many Nat)) (Vec Atom how-many)))
Π> (define peas (lambda (how-many) (rec-Nat how-many (the (Vec Atom 0) vecnil) (lambda (len-1 prev-peas) (vec:: 'pea prev-peas)))))
<input>:1.103-1.125: 
  (define peas (lambda (how-many) (rec-Nat how-many (the (Vec Atom 0) vecnil) (lambda (len-1 prev-peas) (vec:: 'pea prev-peas)))))
                                                                                                        ^--------------------^
vec:: requires that the length have add1 at the top, but was used in a context that expects 0 for the length.
```

Thanks again!
