### ISSUE TITLE
pie FILENAME doesn't work

### ISSUE THREAD

**Issue by hongy19** [david-christiansen/pie-hs#12]
hi,
i tried pie filename and get a strange error

```
(base) [hongy19@CN-00000988 bin]$ pie ~/dev/scheme/1.pie
Positioned (Pos 1 2) (Expected "#" [])

```

**Comment by david-christiansen** [comment]
Thanks for the report!

Would you please post the contents of `1.pie`?

**Comment by hongy19** [comment]
thanks for your feedback.
I think i has found root cause: `#lang pie` is mandatory even I don't use racket

**Comment by david-christiansen** [comment]
That's right! The reason is that the two implementations are supposed to be compatible.
