### ISSUE TITLE
Add working build instructions for macOS

### ISSUE THREAD

**Issue by FranklinChen** [david-christiansen/pie-hs#6]
I was able to build on macOS by using Homebrew and Stack by finding https://github.com/yi-editor/yi/issues/795 and running
```
$ brew install icu4c
$ stack setup
$ stack build --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include
```

With just plain Cabal (installed with Homebrew), I failed:
```
$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
$ cabal v2-build --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - text-icu-0.7.0.1 (lib) (requires build)
 - pie-0.1.0.0 (lib) (first run)
 - pie-0.1.0.0 (exe:pie) (first run)
Starting     text-icu-0.7.0.1 (lib)

Failed to build text-icu-0.7.0.1. The failure occurred during the configure
step.
Build log ( /Users/chen/.cabal/logs/ghc-8.6.5/txt-c-0.7.0.1-b2a9d4f5.log ):
Configuring library for text-icu-0.7.0.1..
cabal: Missing dependencies on foreign libraries:
* Missing (or bad) C libraries: icuuc, icui18n, icudata
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
the library files do exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.

cabal: Failed to build text-icu-0.7.0.1 (which is required by exe:pie from
pie-0.1.0.0). See the build log above for details.
```

Also: maybe add a Travis CI build that works for Linux, Windows, macOS?

**Comment by david-christiansen** [comment]
I wasn't able to get this to build with Stack - `stack init` complained about a version mismatch between Quickcheck and something else, and I didn't really see how to continue. Did it successfully generate you a stack.yaml file that you'd be willing to contribute?

In any case, I don't have a Mac, but I'm happy to merge others' instructions! Though perhaps I should just rip out the regexps from the parser and just write a couple little state machines by hand - this is the kind of thing I was trying to avoid by not depending on libraries :-)

A CI build is a good idea.

**Comment by david-christiansen** [comment]
Oh, and while you're here, would you mind trying what `cabal-install` suggests and providing it the library paths that you provided to Stack? It would be good to have working instructions for multiple build tools if possible.

Thanks!

**Comment by david-christiansen** [comment]
90ea442 removed the dependency on text-icu, which should make it easier to build the project in a variety of contexts.

**Comment by david-christiansen** [comment]
See #8 for progress towards CI setup.

**Comment by david-christiansen** [comment]
As of #8, CI is up and running with Travis on GNU/Linux. Mac OS next, once I decipher the instructions.

**Comment by david-christiansen** [comment]
Since #9 now works, it looks to me like building on Mac OS is the same as on GNU/Linux. While I'd still be interested in a Stack build file, I think this is enough for now.

**Comment by FranklinChen** [comment]
I have a very simple `stack.yaml` that works:

```
flags: {}
packages:
- '.'
extra-deps: []
resolver: lts-13.23
```

**Comment by david-christiansen** [comment]
Thanks! I wonder why `stack solver` failed to make it...

In any case, I've added it here: f2c47db63f6b7eb4b1deab3a978

Thanks again!
